// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-farms.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Sign in to Doc Aga to use this tool." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-farms.ts
var list_farms_default = defineTool({
  name: "list_farms",
  title: "List farms",
  description: "List the farms the signed-in Doc Aga user can access, with location and livestock type.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("farms").select("id, name, livestock_type, municipality, province, region, created_at").eq("is_deleted", false).order("created_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { farms: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-animals.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_animals_default = defineTool2({
  name: "list_animals",
  title: "List animals",
  description: "List animals on a farm. Active animals only by default (not deleted, no exit date). Use list_farms first to get a farm id.",
  inputSchema: {
    farm_id: z.string().describe("Farm UUID from list_farms."),
    include_inactive: z.boolean().optional().describe("Include sold/dead/exited animals. Defaults to false."),
    limit: z.number().optional().describe("Max rows to return. Defaults to 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ farm_id, include_inactive, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("animals").select(
      "id, name, ear_tag, breed, gender, birth_date, life_stage, current_weight_kg, is_currently_lactating, exit_date, exit_reason"
    ).eq("farm_id", farm_id).eq("is_deleted", false).order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 100, 1), 500));
    if (!include_inactive) query = query.is("exit_date", null);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { animals: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-animal.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_animal_default = defineTool3({
  name: "get_animal",
  title: "Get animal details",
  description: "Get the full profile of one animal by id, including breeding, weight and lactation fields.",
  inputSchema: {
    animal_id: z2.string().describe("Animal UUID from list_animals.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ animal_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("animals").select("*").eq("id", animal_id).eq("is_deleted", false).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return {
        content: [{ type: "text", text: "No animal found with that id (or no access)." }],
        isError: true
      };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { animal: data }
    };
  }
});

// src/lib/mcp/tools/list-milking-records.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_milking_records_default = defineTool4({
  name: "list_milking_records",
  title: "List milking records",
  description: "List milk production records for a farm within a date range (YYYY-MM-DD), newest first.",
  inputSchema: {
    farm_id: z3.string().describe("Farm UUID from list_farms."),
    start_date: z3.string().optional().describe("Inclusive start date, YYYY-MM-DD."),
    end_date: z3.string().optional().describe("Inclusive end date, YYYY-MM-DD."),
    limit: z3.number().optional().describe("Max rows to return. Defaults to 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ farm_id, start_date, end_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: animals, error: animalsError } = await supabase.from("animals").select("id, name, ear_tag").eq("farm_id", farm_id).eq("is_deleted", false);
    if (animalsError)
      return { content: [{ type: "text", text: animalsError.message }], isError: true };
    const ids = (animals ?? []).map((a) => a.id);
    if (ids.length === 0)
      return {
        content: [{ type: "text", text: "No animals on this farm." }],
        structuredContent: { records: [], total_liters: 0 }
      };
    let query = supabase.from("milking_records").select("id, animal_id, record_date, session, liters, milk_quality, is_sold, sale_amount").in("animal_id", ids).order("record_date", { ascending: false }).limit(Math.min(Math.max(limit ?? 100, 1), 500));
    if (start_date) query = query.gte("record_date", start_date);
    if (end_date) query = query.lte("record_date", end_date);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const nameById = new Map((animals ?? []).map((a) => [a.id, a.name ?? a.ear_tag ?? a.id]));
    const records = (data ?? []).map((r) => ({ ...r, animal: nameById.get(r.animal_id) }));
    const totalLiters = records.reduce((sum, r) => sum + Number(r.liters ?? 0), 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ total_liters: totalLiters, records }, null, 2) }],
      structuredContent: { records, total_liters: totalLiters }
    };
  }
});

// src/lib/mcp/tools/farm-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
function daysAgo(days) {
  const d = /* @__PURE__ */ new Date();
  d.setUTCDate(d.getUTCDate() - days);
  return d.toISOString().slice(0, 10);
}
var farm_summary_default = defineTool5({
  name: "farm_summary",
  title: "Farm summary",
  description: "Herd and production snapshot for a farm: active animal counts by life stage plus milk output over the last N days.",
  inputSchema: {
    farm_id: z4.string().describe("Farm UUID from list_farms."),
    days: z4.number().optional().describe("Production window in days. Defaults to 7.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ farm_id, days }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const window = Math.min(Math.max(days ?? 7, 1), 365);
    const { data: animals, error } = await supabase.from("animals").select("id, life_stage, gender, is_currently_lactating, exit_date").eq("farm_id", farm_id).eq("is_deleted", false);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const active = (animals ?? []).filter((a) => !a.exit_date);
    const byStage = {};
    for (const a of active) {
      const key = a.life_stage ?? "unknown";
      byStage[key] = (byStage[key] ?? 0) + 1;
    }
    const lactating = active.filter((a) => a.is_currently_lactating).length;
    const { data: milk, error: milkError } = await supabase.from("milking_records").select("liters, sale_amount, is_sold").in("animal_id", active.map((a) => a.id)).gte("record_date", daysAgo(window));
    if (milkError)
      return { content: [{ type: "text", text: milkError.message }], isError: true };
    const summary = {
      farm_id,
      active_animals: active.length,
      exited_animals: (animals ?? []).length - active.length,
      lactating_animals: lactating,
      animals_by_life_stage: byStage,
      window_days: window,
      milk_liters: (milk ?? []).reduce((s, r) => s + Number(r.liters ?? 0), 0),
      milk_sales_amount: (milk ?? []).reduce((s, r) => s + Number(r.sale_amount ?? 0), 0)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sxorybjlxyquxteptdyk";
var mcp_default = defineMcp({
  name: "doc-aga",
  title: "doc-aga",
  version: "0.1.0",
  instructions: "Read-only tools for Doc Aga, a livestock farm management app for Filipino farmers. Call `list_farms` first to get a farm id, then use `farm_summary` for a herd/production snapshot, `list_animals` and `get_animal` for herd details, and `list_milking_records` for milk production and sales. All data is scoped to the signed-in user's farms.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_farms_default, farm_summary_default, list_animals_default, get_animal_default, list_milking_records_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
